config/routes.rb
Cofounderlab::Application.routes.draw do
  resources :members do
    collection do
      get :index_members
    end
  end

  root :to => 'members#index'

end

app/models/founder.rb
class Founder < ActiveRecord::Base
  attr_accessible :description, :industry, :level, :location, :lookfor, :name, :photo_url, :title
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :description, :industry, :level, :location, :lookfor, :name, :photo_url, :title

  def self.pro
     5
  end

  def self.new
     1
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/founders_controller.rb
class FoundersController < ApplicationController
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end
  
  def index_members
    @members = Member.all

    respond_to do |format|
      format.html { render :layout => 'index_members'} # index_members.html.erb
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/founders_helper.rb
module FoundersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cofounderlab</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "scaffold" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/index_members.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cofounderlab</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "reset", :media => "all" %>
  <%= stylesheet_link_tag    "homestyle", :media => "all" %>
  <%= stylesheet_link_tag    "old_style_change", :media => "all" %>
  <%= stylesheet_link_tag    "profilecss", :media => "all" %>
  <%= stylesheet_link_tag    "supersized", :media => "all" %>
  <%= stylesheet_link_tag    "supersized_shutter", :media => "all" %>
  <%= stylesheet_link_tag    "themestyle", :media => "all" %>

  <%= javascript_include_tag "application" %>
<script src="http://www.gcmingati.net/wordpress/wp-content/lab/jquery/imagestrip/jquery-1.5.min.js" type="text/javascript"></script>
<script src="http://www.gcmingati.net/wordpress/wp-content/lab/jquery/imagestrip/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="http://www.gcmingati.net/wordpress/wp-content/lab/jquery/imagestrip/jquery.slideviewer.1.2.js" type="text/javascript"></script> 

  <%= csrf_meta_tags %>

  </head>

<body>

   <div id="main_wrapper" class="main_wrapper">

      <!-- header part start -->
      <div id="header" class="header">
         <%= render :partial => 'shared/header' %>
      </div>
      <!-- header part end -->

      <!-- container start -->
      <div class="baseClass">
         <%= yield %>
      </div>
      <!-- containter end -->
   </div>
   <!-- main wrapper end -->


   <!-- footer start -->
   <div id="footer">
         <%= render :partial => 'shared/footer' %>
   </div>
   <!-- footer end -->
</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :lookfor %><br />
    <%= f.text_field :lookfor %>
  </div>
  <div class="field">
    <%= f.label :industry %><br />
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br />
    <%= f.text_field :photo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/_member_large_show.html.erb
<div id="div_<%= member.id %>" class="profileOutLeft">


<!--profileDetails start =================== -->
<div class="profileDetails">



<div class="newIcon proIcon">

<% if member.level == 5 %>
<img width="82" height="85" alt="" src="/assets/pro_user_tag_profile.png">
<% elsif member.level == 1%>
<img width="82" height="85" alt="" src="/assets/new_user_tag.png">
<% else %>

<% end %>
<!--Tool tip starts-->
<div id="tooltp_wrp_pro_home_11059" class="tooltp_wrp_pro_home" style="display: none;">
<div class="tooltp_home_close"><img width="25" height="29" src="/n/images/x.png" id="tooltp_home_close_11059"></div>
<div class="ttipinwrp_home">
<p id="ttip_home_cnt_11059">
Diego is a Pro Member. Learn more about <a href="/pro-membership">Pro Membership</a>.
</p>
<div class="tooltp_arw_home_top"></div>
<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
<!--Tool tip ends-->
</div> 
<h1><%= link_to member.name, member, {style: "text-decoration:none;" } %></h1>
<div class="state"><%= member.location%></div>

<!--slide show starts here-->       
<div class="sldeOuter"><!--slide outer starts-->
<div class="stripViewer" id="mygaltop1" style="width: 445px; height: 300px;">

<ul style="width: 1780px;">
<li id="slide1">  
<div class="img1">
<div class="perDetails2">

<div class="leftSec"><%= link_to (member_path(member)) do %>
<img width="94" height="110" alt="" src="<%=member.photo_url%>">
<% end %>
</div>                  	

<div class="rightSec">
<p class="profile_det"><span class="left">I'm a</span><span class="right">:</span></p><p class="profile_cont"><%= member.title%></p>
<div class="clear"></div>
<p class="profile_det"><span class="left">Looking for a</span><span class="right">:</span></p><p class="profile_cont"><%= member.lookfor%></p>
<div class="clear"></div>
<p class="profile_det"><span class="left">Industry</span><span class="right">:</span></p><p class="profile_cont"><span><%= member.industry %></span></p>
</div>
</div>
<div class="subHead">
<div class="icon_heading2"></div>                                                        
<h3>Seeking someone to join them</h3>
</div>
<p class="subHeadP">
<%= member.description%>
<%= link_to (member_path(member)) do %>more<% end %>
</p>

</div>
</li>

<li id="slide2">  
<div class="img1">
<div class="subHead">
<div class="icon_strenghts"></div>
<h3>What I'm looking for</h3>
</div>

<div style="width:220px; height:220px; float:left; background-color:#f1f2f4; padding:5px 0px 0px 5px;">
<div>
<b style="float:left; width:38px; margin-right:65px;">Skills</b>	
<b style="float:left; width:107px; text-align:center;">Desired experience level</b>
</div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Finance</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Managing People</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Marketing</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Product Management</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Sales</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Technical</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
            </div>
<div style="float:left; width:190px; margin-left:10px;">
<div style="width:170px; height:150px; float:left; background-color:#F1F2F4; padding:5px 0px 10px 10px; margin-bottom:5px;">
<b>Desired <br>Investment From you</b>
<div style="margin-top:5px;" class="money">
                <img width="95" height="60" alt="" src="/n/themes/basic/images/invester_images.png" style=" ">
<p style="float:left;padding-top:5px; width:140px; font-size:11px; font-style:italic;">Can offer equal investment as my Co-Founder ($5,000-$10,000)</p>
</div>
</div>
<div align="left" style="width:170px; height:45px; float:left;  background-color:#F1F2F4; padding-left:10px; padding-bottom:10px;">
<b style="float:right; width:170px;">Desired time commitment:</b>
<!--Cash Investment :  -->

<p style="float:left;">
</p><p style="float: left; padding-top: 5px; width: 140px; font-size: 11px; font-style: italic;">Part time</p>                                                            <p></p>
</div>
</div>

<div class="clear"></div>
</div>
</li>
<li id="slide3">  
<div class="img1">
<div class="subHead">
<div class="icon_businessStages_new"></div>
<h3><span style="float:left;">Business Stage<strong>:</strong> </span> <div class="busns_stage" style="">&nbsp;Business Plan Drafted</div> </h3>
</div>
<br>
<img width="390" height="177" alt="" src="/n/themes/basic/images/roadmapS_2.png">
<br><br>
<div class="clear"></div>
</div>
</li>

<!--last slide****************************************************************-->
<li id="slide6">  
<div class="slide">
<div class="subHead">
<div class="icon_contactus"></div>
<div class="contactinfo"></div>
<h3>Contact Information</h3>
</div>
<br>
<div style="width:400px; margin-bottom:100px;" class="contactOuter">
<!--*****************************MESSAGE BUTTON***************************************-->
<div class="clear"></div>
<div id="11059" class="lefticon">
<img width="162" height="23" onclick="return sendMail('send message',11059)" alt="" src="/n/themes/basic/images/send_message.png" class="msgusr_button_11059">
<div style="width:50px; float:right; display:none; margin-right:180px;" id="loading11059"><img width="16" height="16" src="/n/images/ajax-loader.gif"> Processing...</div>
</div>
<!--*****************************MESSAGE BUTTON***************************************-->
<br>
<div class="clear"></div>
<div class="Outer"><strong>Learn more about me</strong><div class="horizoOuter"><div class="horizontal"><a class="pleaseLoginProfile" href="#"><img width="24" height="24" border="0" alt="" src="/n/images/services/2_icon.png"></a></div></div></div><div class="clear"></div></div>                                                            <br><br>
<input type="hidden" value="" id="logged_user" name="logged_user">

</div>

</li>
<!--last slide****************************************************************-->
</ul>

</div><table align="center" style="margin:auto;"><tbody><tr><td><div id="stripTransmitter0" class="stripTransmitter" style="width: auto;"><ul><li><a href="#" title="Basic Profile" class="slide1_normal current">&nbsp;</a></li><li><a href="#" title="What I/You bring" class="slide2_normal">&nbsp;</a></li><li><a href="#" title="Business Stage" class="slide3_normal">&nbsp;</a></li><li><a href="#" title="Contact Info" class="slide6_normal">&nbsp;</a></li></ul></div></td></tr></tbody></table>
</div>	<!--slide outer ends-->

<!--slide show ends here-->

<div style="left:115px;" class="left_arrow">
<a class="left_right_mygaltop1 left_arrow_a" href="">
<img width="30" height="30" alt="" src="/assets/left_ar.png"></a> 
</div>
<div style="left:314px;" class="right_arrow">
<a class="left_right_mygaltop1 right_arrow_a" href="">
<img width="30" height="30" alt="" src="/assets/right_ar.png"></a>
</div>


<div class="bottom">
<div class="iconOuter">
						<div class="fav_nt_sig" id="user_11059"></div>
				<p>Save to my favorites</p>
</div>
<div class="iconOuter">
<div class="block_profile block_profile_not_login" id="block_profile_11059"></div>
<p>Don't Show</p>
</div>
<div class="iconOuter">
<div id="fav_msg_11059" class="fav_msg"></div>
</div>

<%= link_to (member_path(member)) do %>
<img width="99" height="35" border="0" alt="" src="/assets/readmore.png">
<% end %>
</div>


</div> 
<!--profileDetails end =================== -->

</div>

app/views/members/_member_show.html.erb
<div id="div_11059" class="profileOutLeft">


<!--profileDetails start =================== -->
<div class="profileDetails">



<div class="newIcon proIcon">
<img width="82" height="85" alt="" src="/n/themes/basic/images/pro_user_tag_profile.png">
<!--Tool tip starts-->
<div id="tooltp_wrp_pro_home_11059" class="tooltp_wrp_pro_home" style="display: none;">
<div class="tooltp_home_close"><img width="25" height="29" src="/n/images/x.png" id="tooltp_home_close_11059"></div>
<div class="ttipinwrp_home">
<p id="ttip_home_cnt_11059">
Diego is a Pro Member. Learn more about <a href="/pro-membership">Pro Membership</a>.
</p>
<div class="tooltp_arw_home_top"></div>
<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
<!--Tool tip ends-->
</div> 
<h1><a style="text-decoration:none;" href="/profile/brooklyn-ny-business-developer-software-diego-regules-11059">Diego Regules</a></h1>
<div class="state">Brooklyn</div>

<!--slide show starts here-->       
<div class="sldeOuter"><!--slide outer starts-->
<div class="stripViewer" id="mygaltop1" style="width: 445px; height: 300px;">

<ul style="width: 1780px;">
<li id="slide1">  
<div class="img1">
<div class="perDetails2">

<div class="leftSec"><a href="/profile/brooklyn-ny-business-developer-software-diego-regules-11059"><img width="94" height="110" alt="" src="/users/u11059_1364229261.jpg"></a></div>                  	
<div class="rightSec">
<p class="profile_det"><span class="left">I'm a</span><span class="right">:</span></p><p class="profile_cont">Business Developer</p>
<div class="clear"></div>
<p class="profile_det"><span class="left">Looking for a</span><span class="right">:</span></p><p class="profile_cont">Programmer/Developer</p>
<div class="clear"></div>
<p class="profile_det"><span class="left">Industry</span><span class="right">:</span></p><p class="profile_cont"><span>Software</span></p>
</div>
</div>
<div class="subHead">
<div class="icon_heading2"></div>                                                        <h3>Seeking someone to join them</h3>
</div>
<p class="subHeadP">
Hello, my name Diego and I am passionate about business and technology. I currently work as an IT Risk Consultant at a Big-4.
Simultaneously I'm starting a venture on the side in the social commerce arena.
I am looking for a passionate front-end developer with superb UX skills... <a href="/profile/brooklyn-ny-business-developer-software-diego-regules-11059">more</a>                                                    </p>
</div>
</li>

<li id="slide2">  
<div class="img1">
<div class="subHead">
<div class="icon_strenghts"></div>
<h3>What I'm looking for</h3>
</div>

<div style="width:220px; height:220px; float:left; background-color:#f1f2f4; padding:5px 0px 0px 5px;">
<div>
<b style="float:left; width:38px; margin-right:65px;">Skills</b>	
<b style="float:left; width:107px; text-align:center;">Desired experience level</b>
</div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Finance</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Managing People</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Marketing</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Product Management</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Sales</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
                            <div style="float:none;" class="strengthStars">
                                                    <p style="width:128px; float:left;">Technical</p>

                                                        <img width="72" height="22" alt="" src="/n/themes/basic/images/0_star.png">
                                            </div>
<div class="clear"></div>
            </div>
<div style="float:left; width:190px; margin-left:10px;">
<div style="width:170px; height:150px; float:left; background-color:#F1F2F4; padding:5px 0px 10px 10px; margin-bottom:5px;">
<b>Desired <br>Investment From you</b>
<div style="margin-top:5px;" class="money">
                <img width="95" height="60" alt="" src="/n/themes/basic/images/invester_images.png" style=" ">
<p style="float:left;padding-top:5px; width:140px; font-size:11px; font-style:italic;">Can offer equal investment as my Co-Founder ($5,000-$10,000)</p>
</div>
</div>
<div align="left" style="width:170px; height:45px; float:left;  background-color:#F1F2F4; padding-left:10px; padding-bottom:10px;">
<b style="float:right; width:170px;">Desired time commitment:</b>
<!--Cash Investment :  -->

<p style="float:left;">
</p><p style="float: left; padding-top: 5px; width: 140px; font-size: 11px; font-style: italic;">Part time</p>                                                            <p></p>
</div>
</div>

<div class="clear"></div>
</div>
</li>
<li id="slide3">  
<div class="img1">
<div class="subHead">
<div class="icon_businessStages_new"></div>
<h3><span style="float:left;">Business Stage<strong>:</strong> </span> <div class="busns_stage" style="">&nbsp;Business Plan Drafted</div> </h3>
</div>
<br>
<img width="390" height="177" alt="" src="/n/themes/basic/images/roadmapS_2.png">
<br><br>
<div class="clear"></div>
</div>
</li>

<!--last slide****************************************************************-->
<li id="slide6">  
<div class="slide">
<div class="subHead">
<div class="icon_contactus"></div>
<div class="contactinfo"></div>
<h3>Contact Information</h3>
</div>
<br>
<div style="width:400px; margin-bottom:100px;" class="contactOuter">
<!--*****************************MESSAGE BUTTON***************************************-->
<div class="clear"></div>
<div id="11059" class="lefticon">
<img width="162" height="23" onclick="return sendMail('send message',11059)" alt="" src="/n/themes/basic/images/send_message.png" class="msgusr_button_11059">
<div style="width:50px; float:right; display:none; margin-right:180px;" id="loading11059"><img width="16" height="16" src="/n/images/ajax-loader.gif"> Processing...</div>
</div>
<!--*****************************MESSAGE BUTTON***************************************-->
<br>
<div class="clear"></div>
<div class="Outer"><strong>Learn more about me</strong><div class="horizoOuter"><div class="horizontal"><a class="pleaseLoginProfile" href="#"><img width="24" height="24" border="0" alt="" src="/n/images/services/2_icon.png"></a></div></div></div><div class="clear"></div></div>                                                            <br><br>
<input type="hidden" value="" id="logged_user" name="logged_user">

</div>

</li>
<!--last slide****************************************************************-->
</ul>

</div><table align="center" style="margin:auto;"><tbody><tr><td><div id="stripTransmitter0" class="stripTransmitter" style="width: auto;"><ul><li><a href="#" title="Basic Profile" class="slide1_normal current">&nbsp;</a></li><li><a href="#" title="What I/You bring" class="slide2_normal">&nbsp;</a></li><li><a href="#" title="Business Stage" class="slide3_normal">&nbsp;</a></li><li><a href="#" title="Contact Info" class="slide6_normal">&nbsp;</a></li></ul></div></td></tr></tbody></table>
</div>	<!--slide outer ends-->

<!--slide show ends here-->

<div style="left:115px;" class="left_arrow">
<a class="left_right_mygaltop1 left_arrow_a" href="">
<img width="30" height="30" alt="" src="/n/themes/basic/images/left_ar.png"></a> 
</div>
<div style="left:314px;" class="right_arrow">
<a class="left_right_mygaltop1 right_arrow_a" href="">
<img width="30" height="30" alt="" src="/n/themes/basic/images/right_ar.png"></a>
</div>


<div class="bottom">
<div class="iconOuter">
						<div class="fav_nt_sig" id="user_11059"></div>
				<p>Save to my favorites</p>
</div>
<div class="iconOuter">
<div class="block_profile block_profile_not_login" id="block_profile_11059"></div>
<p>Don't Show</p>
</div>
<div class="iconOuter">
<div id="fav_msg_11059" class="fav_msg"></div>
</div>

<a href="/profile/brooklyn-ny-business-developer-software-diego-regules-11059"><img width="99" height="35" border="0" alt="" src="/n/themes/basic/images/readmore.png"></a>
</div>


</div> 
<!--profileDetails end =================== -->

</div>

app/views/members/_member_small_show.html.erb
<div style="height:221px;" id="div_<%= member.id %>" class="profileOutLeft">


<!--profileDetails start =================== -->
<div style="height:175px;" class="profileDetails">



<div class="newIcon">
<% if member.level == 5 %>
<img width="82" height="85" alt="" src="/assets/pro_user_tag_profile.png">
<% elsif member.level == 1%>
<img width="82" height="85" alt="" src="/assets/new_user_tag.png">
<% else %>

<% end %>

<!--Tool tip starts-->
<div id="tooltp_wrp_pro_home_13778" class="tooltp_wrp_pro_home">
<div class="tooltp_home_close"><img width="25" height="29" src="/n/images/x.png" id="tooltp_home_close_13778"></div>
<div class="ttipinwrp_home">
<p id="ttip_home_cnt_13778">
Sonny is a Pro Member. Learn more about <a href="/pro-membership">Pro Membership</a>.
</p>
<div class="tooltp_arw_home_top"></div>
<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
<!--Tool tip ends-->
</div> 
<h1><%= link_to member.name, member, {:style =>"text-decoration:none;"} %></h1>
<div class="state_sec"><%= member.location %></div>


<div style="height:145px;" class="img1">
<div class="perDetails2">

<div class="leftSec">
<%= link_to (member_path(member)) do %>
<img width="94" height="110" alt="" src="<%=member.photo_url%>">
<% end %>
</div>                  	
<div style="border:none;" class="rightSec">
<p class="profile_det"><span class="left">I'm a</span><span class="right">:</span></p><p class="profile_cont"><%= member.title %></p>
<div class="clear"></div>
<p class="profile_det"><span class="left">Looking for a</span><span class="right">:</span></p><p class="profile_cont"><%= member.lookfor %></p>
<div class="clear"></div>
<p class="profile_det"><span class="left">Industry</span><span class="right">:</span></p><p class="profile_cont"><span><%= member.industry %>
</span>
</p>
<div class="clear"></div>


<%= link_to member_path(member), {:style => "float:right;margin-right:-10px;"} do %>
<img width="99" height="35" border="0" alt="" src="/assets/readmore.png">
<% end %>

</div>
</div>
</div>


</div> 
<!--profileDetails end =================== -->

</div>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<div class="banner">
</div>

<h1>Listing members</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Title</th>
    <th>Lookfor</th>
    <th>Industry</th>
    <th>Description</th>
    <th>Level</th>
    <th>Photo url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.name %></td>
    <td><%= member.location %></td>
    <td><%= member.title %></td>
    <td><%= member.lookfor %></td>
    <td><%= member.industry %></td>
    <td><%= member.description %></td>
    <td><%= member.level %></td>
    <td><%= member.photo_url %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Location:</b>
  <%= @member.location %>
</p>

<p>
  <b>Title:</b>
  <%= @member.title %>
</p>

<p>
  <b>Lookfor:</b>
  <%= @member.lookfor %>
</p>

<p>
  <b>Industry:</b>
  <%= @member.industry %>
</p>

<p>
  <b>Description:</b>
  <%= @member.description %>
</p>

<p>
  <b>Level:</b>
  <%= @member.level %>
</p>

<p>
  <b>Photo url:</b>
  <%= @member.photo_url %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>